service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  # setup profile for AWS CLI.
  profile: sandx

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById :
    handler: handler.getProductsById 
    events:
      - httpApi:
          path: /products/{productId}
          method: get

plugins:
  - serverless-plugin-typescript
